export enum ExerciseType {
  STRENGTH = 'STRENGTH',
  CARDIO_TREADMILL = 'CARDIO_TREADMILL',
  CARDIO_GENERIC = 'CARDIO_GENERIC',
  BODYWEIGHT = 'BODYWEIGHT',
}

export enum EquipmentCategory {
  BARBELL = 'BARBELL',
  DUMBBELL = 'DUMBBELL',
  CABLE = 'CABLE',
  MACHINE = 'MACHINE',
  SMITH = 'SMITH',
  BODYWEIGHT = 'BODYWEIGHT',
  TREADMILL = 'TREADMILL',
  STATIONARY_BIKE = 'STATIONARY_BIKE',
  STAIR_MASTER = 'STAIR_MASTER',
  ROWING_MACHINE = 'ROWING_MACHINE',
  ELLIPTICAL = 'ELLIPTICAL',
  OTHER = 'OTHER',
}
