onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - argon2
  - esbuild
  - msgpackr-extract
  - prisma
  - unrs-resolver
  - workerd

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
  workerd: true
